name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: dotnet publish -p:PublishSingleFile=true -p:CommitHash=${{ github.sha }} -p:CommitRef=${{ github.ref_type }}/${{ github.ref_name }} -r win-x64 -c ${{ matrix.configuration }} --self-contained false .\Bloxstrap\Bloxstrap.csproj

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: Bloxstrap (${{ matrix.configuration }})
        path: |
          .\Bloxstrap\bin\${{ matrix.configuration }}\net8.0-windows\win-x64\publish\*